import {
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  Carousel,
  CarouselContent,
  CarouselItem,
} from "@repo/ui/components/ui";
import AutoScroll from "embla-carousel-auto-scroll";
import { ArrowRight, Wrench } from "lucide-react";
import React from "react";

export default function UnsoldJobsSection() {
  return (
    <Card className="relative col-span-full">
      <CardHeader className="flex-row items-center justify-between">
        <CardTitle>Unsold Jobs</CardTitle>

        <Button className="w-[100px]" variant="outline" size="sm">
          View All
        </Button>
      </CardHeader>
      <CardContent>
        <Carousel
          opts={{
            dragFree: true,
            loop: true,
          }}
          plugins={[
            AutoScroll({
              playOnInit: true,
              speed: 0.75,
              stopOnInteraction: false,
              direction: "backward",
            }),
          ]}
        >
          <CarouselContent>
            {Array.from({ length: 6 }, (_, i) => i + 1).map((item) => (
              <CarouselItem
                key={item}
                className="min-w-[250px] basis-1/2 md:basis-1/3 xl:basis-1/5"
              >
                <Button
                  variant="outline"
                  className="flex w-full flex-col gap-2 rounded-lg border border-gray-300 px-3 py-2 font-inter"
                >
                  <div className="inline-flex w-full items-center justify-between">
                    <div className="inline-flex flex-col items-start justify-start">
                      <div className="whitespace-nowrap text-sm font-medium text-gray-900">
                        Joseph Aaron
                      </div>
                      <div className="flex items-center gap-1 text-xs font-semibold text-gray-500">
                        Tune-up
                        <Wrench className="size-4 text-primary-light" />
                      </div>
                    </div>
                    <div className="flex h-6 w-8 items-center justify-center rounded-full bg-primary">
                      <ArrowRight className="size-5 text-white" />
                    </div>
                  </div>
                  <div className="flex w-full justify-between">
                    <div className="text-xs font-normal text-gray-900/50">
                      Generated by Google
                    </div>
                    <div className="text-xs font-normal text-gray-900/50">
                      10/11/2024
                    </div>
                  </div>
                </Button>
              </CarouselItem>
            ))}
          </CarouselContent>
        </Carousel>
      </CardContent>
    </Card>
  );
}
